### PR TITLE
Add template to use with [ISO] shortcode on summer.ok.ubc.ca

### PR DESCRIPTION
**Pull request by jamieedwards**
Unable to test this locally due to missing UBC\Helpers

### CODE REVIEW

**Comment by brabbins** [comment]
I can provide you with UBC/Helpers for testing?

**Comment by jamieedwards** [comment]
thanks @brabbins that would be terrific. I've emailed you.

**Comment by jamieedwards** [comment]
Thanks Richard, it's a bit sloppy, I'll fix it up.

**Comment by jamieedwards** [comment]
I've tested locally and it's ready to go except for one thing. I had been using the [plain_cat_slug] shortcode, that hasn't been included in the UBC Helpers, I have emailed David asking if that is something you could add to the helpers, if not, it's no biggie, I can just use tags and let my user know the change for when they are adding new posts. Let me know. Thanks guys!

**Comment by richardtape** [comment]
`get_plain_terms()` can do what you need. It's a more generic function than was in the ISO Loop shortcode. Look at the arguments to the function and what it does.

Start here: https://github.com/ubc/ubc-helpers/blob/master/ubc-helpers.php#L156

**Comment by richardtape** [comment]
Any movement on this @jamieedwards ?

**Comment by jamieedwards** [comment]
@richardtape, this should be good to go now.

**Pull request merged**
