### PR TITLE
Template education programs

### PR DESCRIPTION
**Pull request by cdavis-ubc**

### CODE REVIEW

**Comment by richardtape** [comment]
I'm not sure what's going on here.

Are you basically just changing some esc_html() to wp_kses_post() if so 
I'll fix this up manually.

R

> cdavis-ubc mailto:notifications@github.com
> September 30, 2015 at 3:01 PMvia Postbox 
> 
> ## https://www.postbox-inc.com/?utm_source=email&utm_medium=sumlink&utm_campaign=reach
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/ubc/ubc-use-template-shortcode/pull/26
> 
> ```
>     Commit Summary
> ```
> - Update programs.php
> - Create education-programs.php
>   
>   ```
>   File Changes
>   ```
> - _A_ templates/education/education-programs.php
>   https://github.com/ubc/ubc-use-template-shortcode/pull/26/files#diff-0
>   (147)
> - _M_ templates/education/programs.php
>   https://github.com/ubc/ubc-use-template-shortcode/pull/26/files#diff-1
>   (22)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/ubc/ubc-use-template-shortcode/pull/26.patch
> - https://github.com/ubc/ubc-use-template-shortcode/pull/26.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ubc/ubc-use-template-shortcode/pull/26.

## 

Sent from Postbox 
https://www.postbox-inc.com/?utm_source=email&utm_medium=siglink&utm_campaign=reach

**Comment by cdavis-ubc** [comment]
Yes, manually is probably best.  I just wanted to get my latest version of the template up. That's really all that has changed from my initial pull request.

**Comment by richardtape** [comment]
haha, then, well, that was done a while back ;)

https://github.com/ubc/ubc-use-template-shortcode/commits/master/templates/education/programs.php

27 days ago apparently.

R

> cdavis-ubc mailto:notifications@github.com
> September 30, 2015 at 5:03 PMvia Postbox 
> https://www.postbox-inc.com/?utm_source=email&utm_medium=sumlink&utm_campaign=reach
> 
> Yes, manually is probably best. I just wanted to get my latest version 
> of the template up. That's really all that has changed from my initial 
> pull request.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ubc/ubc-use-template-shortcode/pull/26#issuecomment-144578171.
> 
> cdavis-ubc mailto:notifications@github.com
> September 30, 2015 at 3:01 PMvia Postbox 
> 
> ## https://www.postbox-inc.com/?utm_source=email&utm_medium=sumlink&utm_campaign=reach
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/ubc/ubc-use-template-shortcode/pull/26
> 
> ```
>     Commit Summary
> ```
> - Update programs.php
> - Create education-programs.php
>   
>   ```
>   File Changes
>   ```
> - _A_ templates/education/education-programs.php
>   https://github.com/ubc/ubc-use-template-shortcode/pull/26/files#diff-0
>   (147)
> - _M_ templates/education/programs.php
>   https://github.com/ubc/ubc-use-template-shortcode/pull/26/files#diff-1
>   (22)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/ubc/ubc-use-template-shortcode/pull/26.patch
> - https://github.com/ubc/ubc-use-template-shortcode/pull/26.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ubc/ubc-use-template-shortcode/pull/26.

## 

Sent from Postbox 
https://www.postbox-inc.com/?utm_source=email&utm_medium=siglink&utm_campaign=reach

**Comment by cdavis-ubc** [comment]
Oh I also changed data-toggle=modal to fancybox-inline links.
And added a <a> spanner to add the link to the modal in boxey. 
The template I want to use for the Education programs page is complete in the file 
"education-programs.php" that is in this branch in the education folder.

**Comment by richardtape** [comment]
OK we'll have to discuss this tomorrow. I'll show you how to update your local from the original master.

**Comment by richardtape** [comment]
Remind me; did we 'fix' this template in the clinic, @cdavis-ubc - i.e. can I safely close this PR?

**Comment by cdavis-ubc** [comment]
Yes this template was updated today at the drop-in clinic. This can be closed.

**Pull request closed without merging**
